### ISSUE TITLE
Error running model.run_model with 90 cells

### ISSUE THREAD

**Issue by X201231** [ma-compbio/Fast-Higashi#11]
Hi Ruochi,

I encountered an error when trying to run `model.run_model` on a dataset consisting of 90 cells. The process failed and returned an error message, which I've attached below as a screenshot for reference.

![1730726940646](https://github.com/user-attachments/assets/a06e52cc-e3a2-4585-adfb-f77fa8df88e9)

Is there any parameter within model.run_model that I could adjust to avoid this error? Any advice or suggestions would be greatly appreciated.

Thank you for your help!

**Comment by ruochiz** [comment]
Ah, turn down 256 to be something smaller. it needs to be sth smaller than 90, maybe 64 or 32.

**Comment by X201231** [comment]
I adjusted the `rank` parameter today, and now everything is running smoothly. Thank you for your help!
